site_name: MHSeals Docs
site_url: https://docs.mhsroboboat.com

theme:
  name: material
  font:
    text: Roboto
    code: Fira Code
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: #005A9C
      accent: #191970
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: #005A9C
      accent: #191970
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.path
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.tracking
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit
  logo: assets/seal.png

nav:
  - ... | getting_started/**
  - ...

plugins:
  - search
  - autorefs
  - awesome-pages
  - mkdocs-nav-weight:
      section_renamed: false
      index_weight: -10
      warning: true
      reverse: false
      headless_included: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - toc:
      permalink: true

hooks:
  - hooks.py

copyright: Copyright &copy; 2025 MHS Seals
