site_name: MHCSeals Docs

theme:
  name: material
  font:
    text: Roboto
    code: Fira Code
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.path
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.tracking
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit

nav:
  - Setup:
    - Installing Ubuntu: setup/installing_ubuntu.md
    - Workspace setup: setup/workspace_setup.md
  - Getting Started:
    - ROS2: starting/ros2.md
    - Basic commands: starting/basic_commands.md
    - How2read docs: starting/how2read.md
  - Hardware:
    - VLP-16 (LIDAR): hardware/vlp16.md
    - WIFI Network: hardware/network.md
  - Website:
    - Development: website/index.md
  - Simulation:
    - Gazebo: archive/sim/gazebo.md
    - tf2: archive/sim/tf2.md
    - URDF: archive/sim/urdf.md
  - Archive:
    - kiss_icp: archive/kiss_icp.md
    - MAVROS: archive/mavros.md
    - slam_toolbox: archive/slam_toolbox.md

markdown_extensions:
  - toc:
      permalink: True
copyright: Copyright &copy; 2025 MHS Seals