site_name: MHCSeals Docs

theme:
  name: ivory

nav:
  - Setup:
    - Installing Ubuntu: setup/installing_ubuntu.md
    - Workspace setup: setup/workspace_setup.md
  - Getting Started:
    - ROS2: starting/ros2.md
    - Basic commands: starting/basic_commands.md
    - How2read docs: starting/how2read.md
  - Hardware:
    - VLP-16 (LIDAR): hardware/vlp16.md
    - WIFI Network: hardware/network.md
  - Archive:
    - kiss_icp: archive/kiss_icp.md
    - MAVROS: archive/mavros.md
    - slam_toolbox: archive/slam_toolbox.md
    - Simulation:
      - Gazebo: archive/sim/gazebo.md
      - tf2: archive/sim/tf2.md
      - URDF: archive/sim/urdf.md
