site_name: CS2025 Documentation - MHSeals

theme:
  name: readthedocs

nav:
  - Setup:
    - Installing Ubuntu: setup/installing_ubuntu.md
    - Workspace setup: setup/setting_up_your_workspace.md
  - Getting Started:
    - ROS2: starting/ros2.md
    - MAVROS: starting/mavros.md
  - Hardware:
    - Intel RealSense Camera: hardware/intel_realsense_camera.md
    - VLP-16 LIDAR: hardware/vlp16_lidar.md
  - Navigation:
    - SLAM (Deprecated):
      - nav/kiss_icp.md
      - nav/slam_toolbox.md
      - nav/sim/tf2.md
      - nav/sim/URDF.md
    - Simulation:
      - nav/sim/gazebo.md
